name: 'Keep A Changelog - New Release'
description: 'Automatically update your CHANGELOG.md for a new release. Built for the keepachangelog.com format.'
author: 'Thomas Eizinger'
branding:
  icon: list
  color: white
inputs:
  version:
    description: 'The version of the new release'
    required: true
  date:
    description: 'The date of the release. Defaults to today at the execution time. Accepts any format that Date.parse will accept.'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
